server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zaninluis/trabalholuciano
          search-paths:
          - microservices-java/configs/{application}
          #username: zaninluis
          #password: senha